### ISSUE TITLE
add audio

### ISSUE THREAD

**Issue by shelly96** [shelly96/BoomBastic#35]

**Comment by Ja-ste** [comment]
-  audio water sound (background)
- audio bomb explosion
- audio gameover sound

**Comment by Ja-ste** [comment]
- audio coin collect

**Comment by shelly96** [comment]
Audio still to be implemented:
- bomb explosion
- game over sound
- (optional) start sound
- click sound (play, replay, and how to play)
- splash when objects fall into the water
- wood sound when objects fall on the boat
- (optional) sound if the pirat lost a life
